apiVersion: v1
kind: Service
metadata:
  name: nginx-{{.Release.Name}}
  namespace: web-{{.Release.Name}}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-nginx
      name: http
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-status
    - port: 9113
      protocol: TCP
      targetPort: 9113
      name: metrics
  selector:
    app: nginx-{{.Release.Name}}
  type: NodePort