apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring-{{.Release.Name}}
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 32000
  selector:
    app: grafana
  type: NodePort