apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring-{{.Release.Name}}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'nginx-exporter'
        scrape_interval: 1m
        metrics_path: '/metrics'
        static_configs:
          - targets: ['nginx-{{.Release.Name}}.web-{{.Release.Name}}.svc.cluster.local:9113']
 