apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: web-{{.Release.Name}}
data:
  nginx.conf: |
    server {
        listen       8080;
        location /nginx_status {
            stub_status;
        }
    }
